server:
  host: localhost
  port: 8888
  env: local

repository-mode: postgres #default: in-memory

postgres:
  user: postgres
  password: postgres
  name: mydb
  port: 5432
  host: localhost #for docker: "container-name"
  migrate: true
  sslmode: disable