server:
  host: localhost
  port: :8888
  env: local

repository-mode: postgres

postgres:
  user: postgres
  password: postgres
  name: mydb
  port: 5432
  host: localhost #postgres 
  migrate: true
  sslmode: disable