package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.70

import (
	"context"
	"fmt"

	"github.com/aAmer0neee/comments-service-test-task/graph/model"
	"github.com/aAmer0neee/comments-service-test-task/graph/runtime"
)

// Article is the resolver for the article field.
func (r *mutationResolver) Article(ctx context.Context) (*model.ArticleMutation, error) {
	panic(fmt.Errorf("not implemented: Article - article"))
}

// Mutation returns runtime.MutationResolver implementation.
func (r *Resolver) Mutation() runtime.MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
