package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.70

import (
	"context"
	"fmt"

	"github.com/aAmer0neee/comments-service-test-task/graph/model"
)

// ListArticle is the resolver for the listArticle field.
func (r *queryResolver) ListArticle(ctx context.Context) (*model.ListArticleQuery, error) {
	panic(fmt.Errorf("not implemented: ListArticle - listArticle"))
}
