package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.70

import (
	"context"
	"fmt"

	"github.com/aAmer0neee/comments-service-test-task/graph/model"
	"github.com/aAmer0neee/comments-service-test-task/internal/mappers"
)

// GetList is the resolver for the getList field.
func (r *queryResolver) GetList(ctx context.Context, pageNumber int32, pageSize int32) (model.ListArticleGetResponse, error) {
	if response, count, err := r.Service.GetArticlesList(pageNumber, pageSize); err != nil {
		return model.ListArticleGetBadRequest{
			Message: "ошибка получения списка статей",
		}, fmt.Errorf("ошибка получения спика статей")
	} else {
		return model.ListArticleGetOk{
			Articles: mappers.DomainArticlesListToResponse(response),
			Total:    count,
		}, nil
	}
}
